---

- name: GRAYLOG DOCKER TASK | Ensure That Host Directories Exist [NGINX]
  file:
    path: "{{ item.host_dir }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  notify: "nginx_check_config_and_reload_docker"
  with_items: "{{ nginx_directories }}"
  when: install_nginx_reverse_proxy is defined and install_nginx_reverse_proxy == true

- name: GRAYLOG DOCKER TASK | Ensure That Config Files Exist [NGINX]
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  notify: "nginx_check_config_and_reload_docker"
  with_items: "{{ nginx_files }}"
  when: install_nginx_reverse_proxy is defined and install_nginx_reverse_proxy == true
